version: '3'

services:
    mysql:
        build: ./docker/mysql
        ports:
            - 3306:3306
        volumes:
            - ./var/data/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: "courses"
            MYSQL_USER: "courses"
            MYSQL_PASSWORD: "courses"
            MYSQL_ROOT_PASSWORD:
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_ROOT_HOST: "%"
            MYSQL_HOST: "%"
