sulu_core:
    content:
        structure:
            type_map:
                courses: "Sulu\\Component\\Content\\Compat\\Structure\\StructureBridge"

            paths:
                courses:
                    path: "%kernel.project_dir%/config/templates/courses"
                    type: courses

            resources:
                product_contents:
                    datagrid: "Sprungbrett\\Bundle\\CourseBundle\\Model\\Course"
                    types: ["courses"]
                    endpoint: "sprungbrett.get_course-contents"
