sulu_admin:
    resources:
        courses:
            form: ["@SprungbrettCourseBundle/Resources/config/forms/Course.Course.xml"]
            datagrid: "Sprungbrett\\Bundle\\CourseBundle\\Model\\Course\\Course"
            endpoint: "sprungbrett.get_courses"
