security:
    session_fixation_strategy: none

    access_decision_manager:
        strategy: affirmative

    encoders:
        Sulu\Bundle\SecurityBundle\Entity\User:
            algorithm: sha512
            iterations: 5000
            encode_as_base64: false

    providers:
        sulu:
            id: sulu_security.user_provider

    access_control:
       # needed when firewall on ^/ is used
       # - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       # - { path: /registration, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       # - { path: /password-reset, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       # - { path: /password-forget, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       # - { path: /_fragment, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: /profile, roles: ROLE_USER }
       - { path: /completion, roles: ROLE_USER }

    firewalls:
        example:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: sulu_community.login
                check_path: sulu_community.login
            logout:
                path: sulu_community.logout
                target: /
            remember_me:
                secret:   "%kernel.secret%"
                lifetime: 604800 # 1 week in seconds
                path:     /

sulu_security:
    checker:
        enabled: true
