sprungbrett.courses:
    type: rest
    resource: "@SprungbrettCourseBundle/Controller/CourseController.php"

sprungbrett.course_coutents:
    type: rest
    resource: "@SprungbrettCourseBundle/Controller/CourseContentController.php"

sprungbrett.schedules:
    type: rest
    resource: "@SprungbrettCourseBundle/Controller/ScheduleController.php"
